version: "3.9"

services:
  db:
    container_name: db
    image: postgres:14
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: lanchonete
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    tty: true
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://test:test@db:5432/lanchonete
    volumes:
      - ./src:/app/src
    ports:
      - 8000:8000
    depends_on:
      - db
      

volumes:
  pgdata: