apiVersion: apps/v1
kind: Deployment
metadata:
  name: apptechchallenge-deployment
  labels:
    app: apptechchallenge
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apptechchallenge
  template:
    metadata:
      labels:
        app: apptechchallenge
    spec:
      containers:
      - name: apptechchallenge
        image: 992382363343.dkr.ecr.us-east-2.amazonaws.com/apptechchallenge-repo:latest
        ports:
        - containerPort: 8000
        env:
        - name: TYPEORM_HOST
          value: techchallenge-fiap-rdsdbinstance-faymyf2cxqj6.c9qyy4w40svf.us-east-2.rds.amazonaws.com
        - name: TYPEORM_USERNAME
          value: masteruser
        - name: TYPEORM_PASS
          value: 5EGOy5Glo646
        - name: TYPEORM_DATABASE
          value: lanchonete